/**
 * [389] Find the Difference
 * 
 * difficulty: Easy
 * 
 * TestCase Example: "abcd" "abcde"
 * 
 * https://leetcode-cn.com/problems/find-the-difference/
 * 
 * 
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 * 
 * 
 * >>>>>>中文描述<<<<<<
 * 
 * 
 * [389] 找不同
 * 
 * 
 * 给定两个字符串 s 和 t，它们只包含小写字母。
 * 
 * 字符串 t 由字符串 s 随机重排，然后在随机位置添加一个字母。
 * 
 * 请找出在 t 中被添加的字母。
 * 
 *  
 * 
 * 示例:
 * 
 * 输入：
 * s = "abcd"
 * t = "abcde"
 * 
 * 输出：
 * e
 * 
 * 解释：
 * 'e' 是那个被添加的字母。
 * 
 */
public class E_389_FindTheDifference {
    public char findTheDifference(String s, String t) {
        
    }
}